services:
  psql-db-write:
    image: postgres:9
    container_name: postgres9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

  psql-db-read:
    image: postgres:9
    container_name: postgres9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'

  product:
    container_name: product-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - psql-db-read
      - psql-db-write
